### ISSUE TITLE
osgeo fork in organization necessary?

### ISSUE THREAD

**Issue by dkastl** [pgRouting/admin#17]
@cvvergara , is the `osgeo` fork in the pgRouting organization still necessary?
https://github.com/pgRouting/osgeo

Since you are now SAC member with all possible rights ;-)
I would suggest to remove it, if it's not used and doesn't contain information, that the main one doesn't.

**Comment by cvvergara** [comment]
No, please delete

**Comment by dkastl** [comment]
I think you were faster

**Comment by cvvergara** [comment]
yeah :)

**Comment by dkastl** [comment]
1 day behind and still faster ;-)
