### ISSUE TITLE
Moving RFC's from Wiki to the repository

### ISSUE THREAD

**Issue by dkastl** [pgRouting/admin#19]
@cvvergara , you asked for comments on RFC-3, and I thought, what a pity, that I cannot make the comments or suggestions right at the document. Do I need to respond on the mailing list, or should I just edit the Wiki page?

So I thought, what about moving the RFC documents into a regular Git repository? I don't know, which repository, but probably the `admin` one. If the documents are tracked there, then we can use pull requests to suggest changes. And if the original RFC is a `WIP` pull request, we can also use the pull request annotation and commenting function.

Once a RFC pull request would be merged, it could be `adopted`.

Thoughts?

**Comment by cayetanobv** [comment]
@dkastl Looks good to me

**Comment by cvvergara** [comment]
I just moved them.
https://github.com/pgRouting/admin/wiki#rfc

**Comment by cvvergara** [comment]
https://github.com/pgRouting/admin/tree/master/RFC

**Comment by cvvergara** [comment]
So, also made a PR about RFC2
for us to be merged, we wait until all of us reveiw it and approve it
Kinda having a voting system using the reviews

**Comment by dkastl** [comment]
Looks good. Thanks, Vicky!
