### ISSUE TITLE
Update pgRouting "one-liner"

### ISSUE THREAD

**Issue by dkastl** [pgRouting/admin#6]
Currently pgRouting calls itself "Routing in the database", but in the meanwhile it's much more, and the slogan doesn't reflect that. Let's think about some better sentence.

What are pgRouting's key functionalities:
* Routing
* Network analysis
* Optimization

**Comment by cvvergara** [comment]
@dkastl 
Routing and Graph algorithms in the database

**Comment by cvvergara** [comment]
Made the change
